test:
	@$(MAKE) -sk test-all

test-all:	test-scripts

test-scripts:
	curl -sLO https://raw.githubusercontent.com/nd-cse-20289-sp22/cse-20289-sp22-assignments/master/reading06/test_scripts.sh
	chmod +x test_scripts.sh
	./test_scripts.sh
